version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mock-oauth2-server:
    image: ghcr.io/navikt/mock-oauth2-server:0.3.4
    ports:
      - "8080:8080"
    environment:
      JSON_CONFIG: "{\"interactiveLogin\":false}"
    hostname: host.docker.internal