apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-auth-azure
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/api/internal/isalive"
    initialDelay: 1
  readiness:
    path: "/api/internal/isready"
    initialDelay: 1
  prometheus:
    enabled: true
    path: "/api/internal/metrics"
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 64Mi
  ingresses:
    - https://dp-auth-azure.intern.dev.nav.no
  env:
    - name: PROVIDER
      value: azure
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
    sidecar:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-auth-azure
