name: Bygg og publiser pakke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      mock-oauth2-server:
        image: ghcr.io/navikt/mock-oauth2-server:0.3.4
        ports:
          - 8080:8080
        env:
          JSON_CONFIG: "{\"interactiveLogin\":false}"
          SERVER_HOSTNAME: "mock-oauth2-server"
        options: "--hostname mock-oauth2-server"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: sudo echo "127.0.0.1 mock-oauth2-server" | sudo tee -a /etc/hosts
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}