name: Deploy test-app

on:
  push:
    branches:

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm"

      - run: npm install --no-save --no-audit --prefer-offline --ignore-scripts
      - run: npm test

  build:
    name: Build and Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@master
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-azure:
    name: Deploy with Azure AD
    needs: [ test, build ]
    if: github.ref == 'refs/heads/feature/v2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-azure.yaml
          PRINT_PAYLOAD: true

  deploy-idporten:
    name: Deploy with IDporten
    needs: [ test, build ]
    if: github.ref == 'refs/heads/feature/v2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-idporten.yaml
          PRINT_PAYLOAD: true
